### ISSUE TITLE
HTML parsing error

### ISSUE THREAD

**Issue by starbomberman** [xptsp/plugin.video.DramaCool#1]
Hi, for some strangle reason kodi did not work so I had to uninstall it, after I had uninstalled it dramacool does not work anymore when I tried to install it again. Links are saying html parsing error encountered.

Although I checked on my other firestick and the links work perfectly fine :/

**Comment by starbomberman** [comment]
> Hi, for some strangle reason kodi did not work so I had to uninstall it, after I had uninstalled it dramacool does not work anymore when I tried to install it again. Links are saying html parsing error encountered.
> 
> Although I checked on my other firestick and the links work perfectly fine :/

I figured out that you need the kodibae repo for it to work

**Comment by xptsp** [comment]
Interesting issue....  What are you installing from the kodibae repository to fix this error?  Cause I get this issue on Kodi on some links, but not others....

**Comment by starbomberman** [comment]
> Interesting issue.... What are you installing from the kodibae repository to fix this error? Cause I get this issue on Kodi on some links, but not others....

Yeah only 2 of my links work. I think it was indigo that did the trick as it installed automatically, but I also installed watchnixtoons... maybe that updated some of the links, I don't know...
